adapted to recent multi-ghc-travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,10 +1,14 @@
 env:
-  - GHCVER=7.6.3
-  - GHCVER=7.8.3
-  - GHCVER=head
-env:
-  global:
-    secure: rRwJ4hbIrQHOB7dnk/rEvbI9ybyzkTKv4ycAc17f2GsXNM6s/l8piZa85o38qxkfopzU50JVLB4/QnaURH/cJoE4oR0GdPDiwMPeDHdPkiKX8RHjdj0kfBvguWckEM0PWumreD0ZU+prieGfY23tjoo4TsJk+e5HgeD1RfuzTa8=
+  - CABALVER=1.18 GHCVER=7.6.3
+  - CABALVER=1.18 GHCVER=7.8.4
+  - CABALVER=head GHCVER=head
+  - global:
+      secure: rRwJ4hbIrQHOB7dnk/rEvbI9ybyzkTKv4ycAc17f2GsXNM6s/l8piZa85o38qxkfopzU50JVLB4/QnaURH/cJoE4oR0GdPDiwMPeDHdPkiKX8RHjdj0kfBvguWckEM0PWumreD0ZU+prieGfY23tjoo4TsJk+e5HgeD1RfuzTa8=
+
+matrix:
+  allow_failures:
+  - env: GHCVER=head
+
 deploy:
   provider: hackage
   username: HiromiIshii
@@ -13,24 +17,31 @@ deploy:
   on:
     all_branches: true
     tags: true
+
 before_install:
-- travis_retry sudo add-apt-repository -y ppa:hvr/ghc
-- travis_retry sudo apt-get update
-- echo "ghc == $GHCVER"
-- travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy
-- export PATH=/opt/ghc/$GHCVER/bin:$PATH
+ - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+ - travis_retry sudo apt-get update
+ - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
+ - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
+
 install:
-- cabal-1.18 update
-- cabal-1.18 install --only-dependencies --enable-tests --enable-benchmarks
+ - cabal --version
+ - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - travis_retry cabal update
+ - cabal install --only-dependencies --enable-tests --enable-benchmarks
+
 script:
-- cabal-1.18 configure --enable-tests --enable-benchmarks -v2
-- cabal-1.18 build
-- cabal-1.18 test
-- cabal-1.18 check
-- cabal-1.18 sdist
-- export SRC_TGZ=$(cabal-1.18 info . | awk '{print $2 ".tar.gz";exit}') ; cd dist/;
-  if [ -f "$SRC_TGZ" ]; then cabal-1.18 install "$SRC_TGZ"; else echo "expected '$SRC_TGZ'
-  not found"; exit 1; fi
-matrix:
-  allow_failures:
-  - env: GHCVER=head
+ - if [ -f configure.ac ]; then autoreconf -i; fi
+ - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
+ - cabal build   # this builds all libraries and executables (including tests/benchmarks)
+ - cabal test
+ - cabal check
+ - cabal sdist   # tests that a source-distribution can be generated
+ - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+   cd dist/;
+   if [ -f "$SRC_TGZ" ]; then
+      cabal install --force-reinstalls "$SRC_TGZ";
+   else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+   fi
